### ISSUE TITLE
Feel free to add our team...

### ISSUE THREAD

**Issue by stefek99** [friedger/eosprojectslondon#1]
https://github.com/tiakansara/kubera

* https://TiaKansara.com
* https://MichalStefanow.com
* http://www.boymaas.nl/
* https://www.linkedin.com/in/kahuna

**Comment by friedger** [comment]
Added in https://github.com/friedger/eosprojectslondon/commit/69b055b0f548a232384bbfe115b1c72c17df1b7d

Thank you!
